---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# SurrConformalDR

<!-- badges: start -->
<!-- badges: end -->

The goal of SurrConformalDR is to ...

## Installation

You can install the development version of SurrConformalDR from [GitHub](https://github.com/) with:

```{r eval=FALSE}
install.packages("devtools")
devtools::install_github("Gaochenyin/SurrConformalDR")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(SurrConformalDR)
## basic example code
# sample size
N <- 1e4
# library for SuperLearner
SL.library <- c('SL.glm')
seed <- 2333
# an example for Gaussian outcomes
df <- genData.conformal(seed = seed, N = N, 
                        outcome.type = 'Continuous',
                        beta.S = 10)
head(df)
```



